/* The rolled look, mounted into the page.
 *
 * Three layers, each independently guarded by P4rtsSlot so any one of them can
 * fail without the others noticing:
 *
 *   backdrop  fixed behind everything, pointer-events:none
 *   cursor    fixed overlay that follows the pointer
 *   (the wordmark FX and CTA are mounted by the components that own them)
 *
 * The backdrop is keyed by slug so switching backgrounds tears the old WebGL
 * context down instead of leaking it — browsers only allow a handful of live
 * contexts, and leaking them is what makes a page die after a dozen rerolls.
 */
import { useDice, entryFor } from './DiceProvider';
import DiceCursor, { OWNS_BACKDROP } from './DiceCursor';
import P4RTS_PROPS from '../../lib/p4rts-props.json';
import P4rtsSlot from './P4rtsSlot';
import './dice-stage.css';


/* TINTING THE UNTINTABLE
 *
 * Roughly a third of the vault's backdrops hardcode their colours in the
 * shader and expose no colour prop at all — nothing passed as a prop can ever
 * reach them, so the `p` key looked broken on those. The only thing that can
 * recolour arbitrary rendered output is a filter on the layer itself.
 *
 * sepia() first collapses the source toward a single warm hue (so even a
 * near-monochrome backdrop has something to shift), saturate() gives it back
 * some punch, and hue-rotate() carries it to the rolled palette's hue. It is
 * applied ONLY to components proven not to respond to props — running it over
 * one that already recolours itself would double-shift and fight the palette.
 */
function tintFor(slug, bgPalette) {
  if (!STATIC_BACKDROPS.has(slug)) return undefined;
  const hue = Math.round(bgPalette?.hue ?? 0);
  return `sepia(0.45) saturate(1.9) hue-rotate(${hue - 40}deg)`;
}

/* Map the rolled palette onto whatever colour props THIS component declares.
 *
 * There is no convention in the vault: across 99 backdrops there are ~103
 * distinct colour prop names, and a component takes anywhere from 0 to 10 of
 * them. Passing one generic `color` recolours almost nothing, and spraying all
 * 103 at everything produces React unknown-prop warnings and can hit props
 * that expect a number rather than a colour.
 *
 * So each component gets exactly the names it declares, filled by role:
 * background-ish props take the palette ground, the rest walk the trio so a
 * component asking for six colours gets six DIFFERENT ones rather than the
 * same accent six times. backdrop-colour-props.json is generated by parsing
 * every component's destructured props — regenerate it if the vault updates.
 */
/* The handful of backdrops that declare NO colour prop at all — nothing passed
 * as a prop can reach them, so they get a CSS filter instead (see tintFor).
 * Derived from the same generated map, so it can never drift out of sync. */
/* Cursors that must render ABOVE the page content.
 *
 * The ambient ones (flock, phantom, ripple) belong behind the text — they are
 * atmosphere, and over the copy they wash it out. lock-on-pointer is different:
 * it draws a reticle AROUND page elements as you hover them, so underneath the
 * content it is simply invisible. Layering is per-cursor, not global. */
const CURSOR_ON_TOP = new Set(['lock-on-pointer']);

const STATIC_BACKDROPS = new Set(
  Object.entries(P4RTS_PROPS)
    .filter(([, v]) => !(v.color?.length || v.colorBg?.length || v.colorArray?.length))
    .map(([k]) => k),
);

function colourPropsFor(slug, pal) {
  const meta = P4RTS_PROPS[slug];
  if (!meta) return {};
  const out = {};
  // props the vault labels color-bg take the palette's ground
  for (const n of meta.colorBg ?? []) out[n] = pal.bg;
  // array-valued colour props take the whole trio
  for (const n of meta.colorArray ?? []) out[n] = pal.trio;
  /* The rest walk a ramp so a component asking for six colours gets six
   * DIFFERENT ones rather than the same accent repeated. */
  const ramp = [pal.acc, pal.b, pal.a, pal.c, pal.trio[0], pal.trio[1], pal.trio[2]];
  (meta.color ?? []).forEach((n, i) => { out[n] = ramp[i % ramp.length]; });
  return out;
}



export default function DiceStage() {
  const d = useDice();
  if (!d) return null;
  const { look, onSlotFail } = d;

  // Most vault backgrounds accept a colour + speed; the ones that don't just
  // ignore these, which is why they can be passed blindly.
  // the backdrop's own palette — see the note in dice.js roll()
  const bp = look.bgPalette ?? look.palette;
  const bgProps = { ...colourPropsFor(look.background, bp), speed: look.motion, amplitude: look.motion };

  return (
    <>
      {/* phantom-pointer and photo-wake ARE the scene — a backdrop under them
        * fights for the same pixels and both read as dead (EDI's OWNS_BACKDROP) */}
      <div
        className="p4d-backdrop"
        aria-hidden="true"
        style={{
          filter: tintFor(look.background, bp),
          visibility: OWNS_BACKDROP.has(look.cursor) ? 'hidden' : undefined,
        }}
      >
        {look.background && (
          <P4rtsSlot
            key={look.background}
            slug={look.background}
            entry={entryFor(look.background)}
            props={bgProps}
            onFail={onSlotFail}
          />
        )}
      </div>

      {look.cursor && <DiceCursor choice={look.cursor} palette={look.palette} />}
    </>
  );
}
