/* The rolled look, mounted into the page.
 *
 * Three layers, each independently guarded by P4rtsSlot so any one of them can
 * fail without the others noticing:
 *
 *   backdrop  fixed behind everything, pointer-events:none
 *   cursor    fixed overlay that follows the pointer
 *   (the wordmark FX and CTA are mounted by the components that own them)
 *
 * The backdrop is keyed by slug so switching backgrounds tears the old WebGL
 * context down instead of leaking it — browsers only allow a handful of live
 * contexts, and leaking them is what makes a page die after a dozen rerolls.
 */
import { useEffect } from 'react';
import { useDice, entryFor } from './DiceProvider';
import DiceCursor from './DiceCursor';
import P4RTS_PROPS from '../../lib/p4rts-props.json';
import RGB_TRIPLET from '../../lib/rgb-triplet-props.json';

/* per-slug overdrive for triplet colours (see colourPropsFor) */
/* loom writes vec4(color*a, a) under SRC_ALPHA blending — alpha is applied
 * twice, so line contribution is uColor*a^2 (a~0.15). Gain compensates. */
const TRIPLET_GAIN = { loom: 4, 'retro-static': 9 };

/* CSS-side amplification for effects whose GL blending squares alpha away.
 * Applied to the SLOT (the canvas), never the layer div — the layer carries
 * the ground colour, and boosting it washed the whole page green. */
const SLOT_BOOST = { loom: 'brightness(3.4) saturate(1.3)' };

/* Backdrops that are plain media, not vault components — win95 family
 * treasures Lakota supplied. bliss is THE wallpaper; windows-boot is a
 * looping boot-sequence tape (muted: autoplay requires it, and a surprise
 * boot chime on every roll would get old fast). */
const BUILTIN_BACKDROPS = {
  bliss: { type: 'image', src: '/retro/bliss.webp' },
  'windows-boot': { type: 'video', src: '/retro/windows-boot.mp4' },
};
import P4rtsSlot from './P4rtsSlot';
import './dice-stage.css';


/* TINTING THE UNTINTABLE
 *
 * Roughly a third of the vault's backdrops hardcode their colours in the
 * shader and expose no colour prop at all — nothing passed as a prop can ever
 * reach them, so the `p` key looked broken on those. The only thing that can
 * recolour arbitrary rendered output is a filter on the layer itself.
 *
 * sepia() first collapses the source toward a single warm hue (so even a
 * near-monochrome backdrop has something to shift), saturate() gives it back
 * some punch, and hue-rotate() carries it to the rolled palette's hue. It is
 * applied ONLY to components proven not to respond to props — running it over
 * one that already recolours itself would double-shift and fight the palette.
 */
function tintFor(slug, bgPalette) {
  if (!STATIC_BACKDROPS.has(slug)) return undefined;
  const hue = Math.round(bgPalette?.hue ?? 0);
  return `sepia(0.45) saturate(1.9) hue-rotate(${hue - 40}deg)`;
}

/* Map the rolled palette onto whatever colour props THIS component declares.
 *
 * There is no convention in the vault: across 99 backdrops there are ~103
 * distinct colour prop names, and a component takes anywhere from 0 to 10 of
 * them. Passing one generic `color` recolours almost nothing, and spraying all
 * 103 at everything produces React unknown-prop warnings and can hit props
 * that expect a number rather than a colour.
 *
 * So each component gets exactly the names it declares, filled by role:
 * background-ish props take the palette ground, the rest walk the trio so a
 * component asking for six colours gets six DIFFERENT ones rather than the
 * same accent six times. backdrop-colour-props.json is generated by parsing
 * every component's destructured props — regenerate it if the vault updates.
 */
/* The handful of backdrops that declare NO colour prop at all — nothing passed
 * as a prop can reach them, so they get a CSS filter instead (see tintFor).
 * Derived from the same generated map, so it can never drift out of sync. */
/* Cursors that must render ABOVE the page content.
 *
 * The ambient ones (flock, phantom, ripple) belong behind the text — they are
 * atmosphere, and over the copy they wash it out. lock-on-pointer is different:
 * it draws a reticle AROUND page elements as you hover them, so underneath the
 * content it is simply invisible. Layering is per-cursor, not global. */
const CURSOR_ON_TOP = new Set(['lock-on-pointer']);

/* Tint via CSS when props can't recolour the ART: components with no
 * FOREGROUND colour props at all. jelly-field only exposes backgroundColor —
 * its purple jelly is hardcoded, so without the filter it ignores the
 * customizer entirely. */
const STATIC_BACKDROPS = new Set(
  Object.entries(P4RTS_PROPS)
    .filter(([, v]) => !(v.color?.length || v.colorArray?.length))
    .map(([k]) => k),
);

/** hex -> shader-style [r,g,b] in 0..1 */
const hex01 = (hex) => {
  const n = parseInt(String(hex).replace('#', ''), 16);
  return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
};

/* Props whose vault type says "array" but which are really WebGL RGB
 * TRIPLETS ([0.5,0.5,0.5]), not lists of hex colours — handing them the
 * palette trio of hex strings garbles the uniform and they render black.
 * loom, retro-static, mercury-flow and oil-slick all failed exactly this way.
 * Auto-detected from each prop's vault default (numeric 3-array = triplet). */


/* Per-backdrop extras that aren't colours. molten-pane's imageSrc defaults to
 * a random Unsplash portrait — it should be Lakota. Drop the real photo at
 * public/images/lakota.jpg and it appears here with no code change. */
const BACKDROP_EXTRAS = {
  'molten-pane': { imageSrc: '/images/lakota.jpg' },
};

function colourPropsFor(slug, pal) {
  const meta = P4RTS_PROPS[slug];
  if (!meta) return {};
  const out = {};
  if (RGB_TRIPLET[slug]) {
    /* Shader triplets multiply: values above 1.0 are legal and act as gain.
     * loom's thin alpha strokes peak ~12% over the ground at 1.0 — authored
     * as a whisper. As the page's whole backdrop it needs to project. */
    const gain = TRIPLET_GAIN[slug] ?? 1;
    out[RGB_TRIPLET[slug]] = hex01(pal.acc).map((v) => v * gain);
  }
  // props the vault labels color-bg take the palette's ground
  for (const n of meta.colorBg ?? []) out[n] = pal.bg;
  // array-valued colour props take the whole trio (unless they're RGB triplets)
  for (const n of meta.colorArray ?? []) if (out[n] === undefined) out[n] = pal.trio;
  /* The rest walk a ramp so a component asking for six colours gets six
   * DIFFERENT ones rather than the same accent repeated. */
  const ramp = [pal.acc, pal.b, pal.a, pal.c, pal.trio[0], pal.trio[1], pal.trio[2]];
  (meta.color ?? []).forEach((n, i) => { out[n] = ramp[i % ramp.length]; });
  return out;
}



/* Backdrops whose render loop is driven by pointer events (input:
 * react-props / self) sit on their first frame until the mouse moves — on
 * touch, forever. molten-pane showed a flat ground until poked. This wakes
 * them with a synthetic move burst on mount and keeps forwarding real
 * pointer moves so refraction-style effects track the hand. Same re-entrancy
 * guard as the cursor bridge: the bubbled copy reaches this listener too. */
function useBackdropWake(background) {
  const input = P4RTS_PROPS[background]?.input;
  /* The vault's input detector isn't complete — molten-pane records null yet
   * reads the pointer via react props. So the wake burst runs for EVERY
   * backdrop (a few synthetic moves are harmless to effects that ignore
   * them), and only the LIVE forwarding is gated: window-listeners would see
   * each real move twice. */
  const forwardLive = input !== 'window';
  useEffect(() => {
    if (!background) return undefined;
    let forwarding = false;
    const send = (x, y) => {
      /* ALL canvases, not querySelector's first: React StrictMode double-
       * mounts in dev, so during the wake window a dead first canvas can sit
       * in front of the live one and swallow every event. And the canvas
       * specifically — dispatched events bubble UP, so hitting a wrapper div
       * never reaches it. */
      let targets = document.querySelectorAll('.p4d-backdrop canvas');
      if (!targets.length) targets = document.querySelectorAll('.p4d-backdrop [data-p4rts] > *');
      const init = { bubbles: true, clientX: x, clientY: y, pointerId: 1, pointerType: 'mouse', isPrimary: true };
      for (const c of targets) {
        c.dispatchEvent(new PointerEvent('pointermove', init));
        c.dispatchEvent(new MouseEvent('mousemove', init));
      }
    };
    const onMove = (e) => {
      if (forwarding) return;
      forwarding = true;
      try { send(e.clientX, e.clientY); } finally { forwarding = false; }
    };
    /* wake burst: a little sweep so the first paint happens without input.
     * The canvas mounts lazily (three.js compiles on first visit in dev), so
     * attempts only count once it EXISTS — a blind 1.8s timer used to expire
     * before the canvas showed up and the wake fizzled. */
    let i = 0;
    const t = setInterval(() => {
      if (!document.querySelector('.p4d-backdrop canvas')) return; // not up yet
      forwarding = true;
      try { send(innerWidth * (0.3 + 0.04 * (i % 12)), innerHeight * (0.35 + 0.02 * (i % 5))); }
      finally { forwarding = false; }
      // spread over ~9s: textures/lazy chunks can land well after the canvas
      if (++i > 30) clearInterval(t);
    }, 300);
    const kill = setTimeout(() => clearInterval(t), 20000);
    if (forwardLive) window.addEventListener('pointermove', onMove, { passive: true });
    return () => {
      clearInterval(t); clearTimeout(kill);
      if (forwardLive) window.removeEventListener('pointermove', onMove);
    };
  }, [background, forwardLive]);
}

export default function DiceStage() {
  const d = useDice();
  const look = d?.look;
  useBackdropWake(look?.background);
  if (!d || !look) return null;
  const { onSlotFail } = d;

  // Most vault backgrounds accept a colour + speed; the ones that don't just
  // ignore these, which is why they can be passed blindly.
  // the backdrop's own palette — see the note in dice.js roll()
  const bp = look.bgPalette ?? look.palette;
  const bgProps = { ...colourPropsFor(look.background, bp), ...BACKDROP_EXTRAS[look.background], speed: look.motion, amplitude: look.motion };

  return (
    <>
      {/* The layer's ground comes from the ART palette, not the page one.
        * Thin-line effects (loom, mote-field, wave-lattice…) paint 1px alpha
        * strokes — over the page's warm mid-dark they wash out to nothing,
        * over their own palette's near-black floor they read. This is also
        * what makes the `p` key visibly recolour the ground. */}
      <div
        className="p4d-backdrop"
        aria-hidden="true"
        style={{ filter: tintFor(look.background, bp), background: bp.bg }}
        data-bg={look.background ?? undefined}
      >
        {BUILTIN_BACKDROPS[look.background]?.type === 'image' && (
          <div
            className="p4d-builtin-bg"
            style={{ backgroundImage: `url(${BUILTIN_BACKDROPS[look.background].src})` }}
          />
        )}
        {BUILTIN_BACKDROPS[look.background]?.type === 'video' && (
          <video
            key={look.background}
            className="p4d-builtin-bg p4d-builtin-video"
            src={BUILTIN_BACKDROPS[look.background].src}
            autoPlay
            loop
            muted
            playsInline
          />
        )}
        {look.background && !BUILTIN_BACKDROPS[look.background] && (
          <P4rtsSlot
            key={look.background}
            slug={look.background}
            entry={entryFor(look.background)}
            props={bgProps}
            onFail={onSlotFail}
          />
        )}
      </div>

      {look.cursor && <DiceCursor choice={look.cursor} palette={look.palette} />}
    </>
  );
}
